spring.application.name=Proyecto 1


spring.datasource.url=https://zvvmngjayeiifdfapuac.supabase.co
spring.datasource.username=veterinaria
spring.datasource.password=zbolll06HB214aRg

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
